local M = {}

-- Rules to find and replace. The order is probably important.
-- Pulled from various sources.
local rules = {
  { "12 midnight", "midnight" },
  { "12 noon", "noon" },
  { "a big fan of", "a fan of" },
  { "a bit more", "more" },
  { "a bit of", "some" },
  { "a considerable amount of" },
  { "a large number of", "many" },
  { "a pretty", "a" },
  { "a rather", "a" },
  { "a slew of" },
  { "absolute minimum", "minimum" },
  { "absolutely" },
  { "access:verb", "get" },
  { "achieve", "get" },
  { "act to" },
  { "actual experience", "experience" },
  { "actually" },
  { "added bonus", "bonus" },
  { "address the problem", "solve the problem" },
  { "address this problem", "solve this problem" },
  { "adjust", "change" },
  { "adjustment", "change" },
  { "advance notice", "notice" },
  { "advance planning", "planning" },
  { "advance reservations", "reservations" },
  { "advance warning", "warning" },
  { "aforementioned" },
  { "after all is said and done" },
  { "all of a sudden", "suddenly" },
  { "all of the", "all the" },
  { "all of these", "these" },
  { "all things considered" },
  { "all-time record", "record" },
  { "allow me to", "I will" },
  { "almost all", "most" },
  { "almost certainly" },
  { "almost completely", "almost" },
  { "almost entirely", "mostly" },
  { "almost everyone", "most people" },
  { "almost never", "seldom" },
  { "along the lines of", "like" },
  { "already exist", "exist" },
  { "am able to", "can" },
  { "ameliorate", "improve" },
  { "amongst", "among" },
  { "amounts to", "is" },
  { "an estimated", "about" },
  { "an individual", "a person" },
  { "analogous", "similar" },
  { "and also", "and" },
  { "and even worse,", "worse," },
  { "anticipate", "expect" },
  { "any and all", "all" },
  { "any given", "any" },
  { "anything resembling" },
  { "apparent" },
  { "apparently" },
  { "append", "add" },
  { "are able to", "can" },
  { "are now wondering", "are wondering" },
  { "are of the opinion that", "believe" },
  { "are presently", "are now" },
  { "aren't nearly", "aren't" },
  { "arrive at the conclusion", "conclude" },
  { "as a matter of fact" },
  { "as a means of", "to" },
  { "as a means to", "to" },
  { "as a while" },
  { "as far as I'm concerned" },
  { "as it truly is" },
  { "as of now", "now" },
  { "as the case may be" },
  { "ascertain", "find out whether" },
  { "ask the question", "ask" },
  { "assist", "help" },
  { "assistance", "help" },
  { "at about", "at" },
  { "at all times" },
  { "at all times", "always" },
  { "at an earlier stage", "earlier" },
  { "at first glance" },
  { "at the earliest possible date", "as soon as possible" },
  { "at the present time", "now" },
  { "at the same time that", "while" },
  { "at this point in time", "now" },
  { "attain", "reach" },
  { "attempt", "try" },
  { "attractive in appearance", "attractive" },
  { "augment", "increase" },
  { "basic fundamental", "fundamental" },
  { "basic fundamentals", "fundamentals" },
  { "basic necessity", "need" },
  { "basically" },
  { "been pretty", "been" },
  { "best possible", "best" },
  { "biannually", "twice a year" },
  { "black in color", "black" },
  { "both of them", "both" },
  { "both of these", "both" },
  { "break apart", "separate" },
  { "brief in duration", "brief" },
  { "but the question remains:" },
  { "by and large" },
  { "by definition" },
  { "by leaps and bounds" },
  { "by means of", "by" },
  { "by means of", "through" },
  { "by virtue of the fact that", "because" },
  { "by virtue of", "by" },
  { "came to a realization", "realized" },
  { "came to an abrupt end", "ended abruptly" },
  { "can be seen as", "is" },
  { "can potentially", "can" },
  { "can truly", "can" },
  { "carefully examines", "examines" },
  { "category", "group" },
  { "cease", "stop" },
  { "clearly evident", "obvious" },
  { "climb up", "climb" },
  { "close proximity", "close" },
  { "close scrutiny", "scrutiny" },
  { "cognizant", "aware" },
  { "combine together", "combine" },
  { "commence", "start" },
  { "common similarities", "similarities" },
  { "compare and contrast", "compare" },
  { "compeltely fulfilled", "fulfilled" },
  { "complete monopoly", "monopoly" },
  { "complete stranger", "stranger" },
  { "completely destroyed", "destroyed" },
  { "completely eliminate", "eliminate" },
  { "conceal", "hide" },
  { "concerning", "about" },
  { "concerting the matter of" },
  { "conduct an investigation into", "investigate" },
  { "consensus", "agreement" },
  { "consequently", "so" },
  { "considered to be", "considered" },
  { "consolidate", "combine" },
  { "construct", "build" },
  { "continue on", "continue" },
  { "contributing factor", "cause" },
  { "convincingly explains", "explains" },
  { "cooperate together", "cooperate" },
  { "cooperate", "help" },
  { "correctional facilities", "jails" },
  { "correctional facility", "jail" },
  { "costs a total of", "costs" },
  { "definitely" },
  { "demise", "death" },
  { "denote", "mean" },
  { "despite the fact that", "although" },
  { "did not succeed", "failed" },
  { "doctorate degree", "doctorate" },
  { "does get", "gets" },
  { "due to the effects", "because" },
  { "due to the fact that", "because" },
  { "during the course of", "during" },
  { "during the month of", "in" },
  { "e.g.", "for example" },
  { "each and every", "each" },
  { "each and every", "every" },
  { "early, primitive", "primitive" },
  { "economically deprived", "poor" },
  { "eliminate", "get rid of" },
  { "encounter", "meet" },
  { "end product", "product" },
  { "end result", "result" },
  { "endeavor", "try" },
  { "enter into", "enter" },
  { "erode away", "erode" },
  { "especially vital", "vital" },
  { "essentially" },
  { "estimated at about", "estimated" },
  { "exact same", "same" },
  { "exactly how", "how" },
  { "exactly identical", "identical" },
  { "exactly the", "the" },
  { "except when", "unless" },
  { "excess verbiage", "verbiage" },
  { "excessive number of", "too many" },
  { "expedite", "hasten" },
  { "expend", "spend" },
  { "expenditure", "cost" },
  { "expenditures", "costs" },
  { "extend an invitation", "invite" },
  { "extremely" },
  { "facility", "ease" },
  { "far beyond", "beyond" },
  { "far, far beyond", "beyond" },
  { "far, far", "far" },
  { "feasible", "possible" },
  { "few in number", "few" },
  { "filled to capacity", "filled" },
  { "filled to the brim", "filled" },
  { "final completion", "completion" },
  { "final conclusion", "conclusion" },
  { "final demise", "demise" },
  { "final outcome", "outcome" },
  { "final result", "result" },
  { "final verdict", "verdict" },
  { "find out", "find" },
  { "first and foremost", "first" },
  { "first began", "began" },
  { "first created", "created" },
  { "first introduced", "introduced" },
  { "first invented", "invented" },
  { "follow after", "after" },
  { "foot pedal", "pedal" },
  { "for all intents and purposes" },
  { "for approximately", "about" },
  { "for that which is", "for the" },
  { "for the most part" },
  { "for the purpose of", "for" },
  { "for the purpose of", "to" },
  { "foreign imports", "imports" },
  { "i should also mention that" },
  { "i guess" },
  { "i think" },
  { "i think, " },
  { "i think that " },
  { "i think that," },
  { "i want to say that" },
  { "i wish to take this opportunity to", "I want to" },
  { "in close proximity to", "near" },
  { "in order that", "so" },
  { "in order to", "to" },
  { "in reality" },
  { "in regard to", "as for" },
  { "in spite of the fact that", "although" },
  { "in spite of", "despite" },
  { "in terms of" },
  { "in the absence of", "without" },
  { "in the area of", "in" },
  { "in the course of", "during" },
  { "in the event of", "if" },
  { "in the event that", "if" },
  { "in the final analysis" },
  { "in the near future", "soon" },
  { "in the process of" },
  { "in the vicinity of", "near" },
  { "in today's society", "today" },
  { "in truth," },
  { "in view of the fact that", "because" },
  { "in which" },
  { "inquire", "ask" },
  { "insitute:verb", "introduce" },
  { "interestingly enough" },
  { "irregardless" },
  { "is able to", "can" },
  { "is aware of the fact that", "knows" },
  { "is found to be", "is" },
  { "is going to", "will" },
  { "is in conflict with", "conflicts with" },
  { "is in contrast with", "contrasts with" },
  { "is making", "makes" },
  { "is of significant importance", "is important" },
  { "is one reason why", "is why" },
  { "is presently", "is now" },
  { "is pretty darn" },
  { "is required", "is needed" },
  { "is scared of", "fears" },
  { "is seen as", "is" },
  { "is when you want to", "is to" },
  { "is when", "is" },
  { "is where" },
  { "it almost seems like" },
  { "it can be seen that" },
  { "it does make", "it makes" },
  { "it does seem", "it's" },
  { "it goes to show that" },
  { "it is clear that" },
  { "it is evident that" },
  { "it is important to keep in mind that" },
  { "it is interesting to note that" },
  { "it is my belief that" },
  { "it is my hope that" },
  { "it is my opinion that" },
  { "it is possible that" },
  { "it is probably that", "probably" },
  { "it seems like" },
  { "it seems that" },
  { "it should be pointed out that" },
  { "it should be pointed out" },
  { "it's worth pointing out that" },
  { "join together", "join" },
  { "just a", "a" },
  { "just to", "to" },
  { "kind of" },
  { "large in size", "large" },
  { "last but not least", "finally" },
  { "last, but not least", "finally" },
  { "later on", "later" },
  { "like," },
  { ", like," },
  { "link together", "link" },
  { "literally" },
  { "made a statement that", "said that" },
  { "made out of", "made of" },
  { "make a decision", "decide" },
  { "make an assumption", "assume" },
  { "make contact with", "contact" },
  { "make reference to", "refer to" },
  { "manner in which", "way" },
  { "manner", "way" },
  { "materialize", "appear" },
  { "may possibly", "may" },
  { "mental attitude", "attitude" },
  { "might possibly", "might" },
  { "might very well", "may" },
  { "minuscule", "tiny" },
  { "mitigate", "reduce" },
  { "mix together", "mix" },
  { "modifications", "changes" },
  { "modify", "change" },
  { "month after month", "each month" },
  { "month of September", "September" },
  { "more and more", "often" },
  { "more often than not" },
  { "more or less" },
  { "more preferable", "preferable" },
  { "more than a few", "some" },
  { "more than adequate", "adequate" },
  { "moreover", "besides" },
  { "mutual agreement", "agreement" },
  { "mutual communication", "communication" },
  { "mutual cooperation", "cooperation" },
  { "mutual friendship", "friendship" },
  { "mutual understanding", "understanding" },
  { "natural instinct", "instinct" },
  { "necessary prerequisite", "prerequisite" },
  { "necessity", "need" },
  { "never once", "never" },
  { "nevertheless", "yet" },
  { "new breakthrough", "breakthrough" },
  { "new development", "development" },
  { "new record", "record" },
  { "none at all", "none" },
  { "not been kind", "been unkind" },
  { "not dissimilar", "like" },
  { "not impossible", "possible" },
  { "not in a position to", "can't" },
  { "not infrequent", "frequent" },
  { "not infrequently", "frequently" },
  { "not many", "few" },
  { "not necessarily", "not" },
  { "not old enough", "too young" },
  { "not possible", "impossible" },
  { "not the same", "different" },
  { "not unlike", "like" },
  { "not unnoticed", "noticed" },
  { "now compare", "compare" },
  { "numerous", "many" },
  { "objective", "goal" },
  { "obtain", "get" },
  { "obviate", "avoid" },
  { "obviously" },
  { "occurred", "happened" },
  { "occurs", "happens" },
  { "of course," },
  { "of great importance", "that's important" },
  { "of major importance", "that's important" },
  { "often times", "often" },
  { "old cliche", "cliche" },
  { "old proverb", "proverb" },
  { "old relic", "relic" },
  { "old saying", "saying" },
  { "on a daily basis", "daily" },
  { "on a frequent basis", "frequently" },
  { "on a monthly basis", "monthly" },
  { "on a regular basis", "regularly" },
  { "on a temporary basis", "temporarily" },
  { "on a weekly basis", "weekly" },
  { "on a yearly basis", "yearly" },
  { "on an annual basis", "annually" },
  { "on an ongoing basis", "ongoing" },
  { "on the contrary", "instead" },
  { "on the other hand" },
  { "on the part of", "by" },
  { "one and the same", "the same" },
  { "one might say that", "perhaps" },
  { "one of the most unique", "unique" },
  { "one possible reason is that", "one reason is" },
  { "one way or another" },
  { "opposite of" },
  { "optimum", "best" },
  { "orchestrate", "organize" },
  { "originally created", "created" },
  { "over-exaggerate", "exaggerate" },
  { "over-exaggeration", "exaggeration" },
  { "overall consensus", "consensus" },
  { "overall total", "total" },
  { "owing to the fact that", "because" },
  { "partially completed", "partly completed" },
  { "partially destroyed", "partly destroyed" },
  { "participate in", "join" },
  { "participate", "take part" },
  { "particular type of", "type of" },
  { "pass away", "die" },
  { "past history", "history" },
  { "past memories", "memories" },
  { "past tradition", "tradition" },
  { "pause momentarily", "pause" },
  { "penetrate into", "penetrate" },
  { "period of time", "period" },
  { "personal opinion", "opinion" },
  { "personal preferences", "preferences" },
  { "pertaining to", "about" },
  { "place an emphasis on", "emphasize" },
  { "place emphasis on", "emphasize" },
  { "point in time", "time" },
  { "ponder on", "ponder" },
  { "possess", "have" },
  { "previously mentioned", "mentioned" },
  { "prior experience", "experience" },
  { "prior to", "before" },
  { "proceed", "go" },
  { "produce an effect", "cause" },
  { "prompt", "cause" },
  { "promptly", "quickly" },
  { "provide a summary", "summarize" },
  { "provide an explanation", "explain" },
  { "provide assistance", "help" },
  { "provide guidance", "guide" },
  { "provide information", "inform" },
  { "provide proof", "prove" },
  { "provide protection", "protect" },
  { "provide support", "support" },
  { "provided that", "if" },
  { "pursuant to" },
  { "put an end to", "end" },
  { "put emphasis on", "emphasize" },
  { "quite possibly", "possibly" },
  { "raise awareness", "raise" },
  { "raise the question", "ask" },
  { "rapidly", "quickly" },
  { "reach a conclusion", "conclude" },
  { "really" },
  { "reason is because", "reason is" },
  { "reason why is because", "reason is" },
  { "receive a gift", "get a gift" },
  { "receive a pardon", "get a pardon" },
  { "receive an education", "get an education" },
  { "reclaim back", "reclaim" },
  { "refer back to", "refer to" },
  { "refer to as", "call" },
  { "regarding", "about" },
  { "reiterate again", "reiterate" },
  { "reiterate once again", "reiterate" },
  { "relatively close", "close" },
  { "remain the same", "remain" },
  { "remunerate", "pay" },
  { "render", "make" },
  { "reoccur", "happen again" },
  { "represents", "is" },
  { "require", "need" },
  { "requirement", "need" },
  { "reside in", "live in" },
  { "reside", "live" },
  { "residence", "home" },
  { "respective", "own" },
  { "retain", "keep" },
  { "retains", "keeps" },
  { "retrieve back", "retrieve" },
  { "right now", "now" },
  { "rise up", "rise" },
  { "satisfactorily", "adequately" },
  { "scrutinize", "examine" },
  { "seek after", "seek" },
  { "seem to be", "seem" },
  { "seem to indicate", "indicate" },
  { "sense of", "sense" },
  { "serious in nature", "serious" },
  { "several different", "different" },
  { "several different", "several" },
  { "several various", "several" },
  { "should be considered", "should" },
  { "should be noted", "note" },
  { "should be pointed out", "note" },
  { "should be taken into consideration", "consider" },
  { "significant breakthrough", "breakthrough" },
  { "significant difference", "difference" },
  { "significant impact", "impact" },
  { "similar to each other", "similar" },
  { "simultaneously", "at the same time" },
  { "slightly different", "slightly" },
  { "small in size", "small" },
  { "small, tiny", "tiny" },
  { "speak to", "talk to" },
  { "still remains", "still" },
  { "strategic plan", "plan" },
  { "strategically planned", "planned" },
  { "strongly believe", "believe" },
  { "subsequent to", "after" },
  { "substantial amount of", "much" },
  { "successfully complete", "complete" },
  { "successfully pass", "pass" },
  { "suddenly and unexpectedly", "suddenly" },
  { "sufficient enough", "sufficient" },
  { "sufficient", "enough" },
  { "summarize briefly", "summarize" },
  { "surrounded on allsides", "surrounded" },
  { "take action", "act" },
  { "take into account", "consider" },
  { "take into consideration", "consider" },
  { "take note of", "note" },
  { "take place", "occur" },
  { "take steps", "act" },
  { "take the opportunity", "take the chance" },
  { "terminate", "end" },
  { "the exact same", "the same" },
  { "the month of May", "May" },
  { "the reason is because", "the reason is" },
  { "the reason why is because", "the reason is" },
  { "the thing is that", "the fact is" },
  { "the truth is that", "in fact" },
  { "the vast majority", "most" },
  { "their own", "their" },
  { "therefore", "so" },
  { "thoroughly", "completely" },
  { "through the course of", "throughout" },
  { "through the use of", "through" },
  { "throughout the duration of", "during" },
  { "time period", "period" },
  { "time when", "time" },
  { "tiny, little", "tiny" },
  { "to a certain extent", "somewhat" },
  { "to a large extent", "largely" },
  { "to all intents and purposes" },
  { "to be able to", "can" },
  { "to be able to", "to" },
  { "to be in a position to", "can" },
  { "together with", "with" },
  { "totally obvious", "obvious" },
  { "totally", "completely" },
  { "transmit", "send" },
  { "transpire", "happen" },
  { "true fact", "fact" },
  { "try and", "try to" },
  { "try to attempt", "try to" },
  { "try to endeavor", "try to" },
  { "try to" },
  { "turn into", "become" },
  { "ultimately", "finally" },
  { "undergo", "experience" },
  { "understand the fact that", "understand that" },
  { "understandably", "naturally" },
  { "unexpected surprise", "surprise" },
  { "unintentional mistake", "mistake" },
  { "unintentionally", "accidentally" },
  { "united as one", "united" },
  { "until such time as", "until" },
  { "upcoming", "future" },
  { "utilization", "use" },
  { "utilize the opportunity", "use the chance" },
  { "utilize the time", "use the time" },
  { "utilize", "use" },
  { "validate", "confirm" },
  { "various different", "various" },
  { "very unique", "unique" },
  { "viewpoint", "point of view" },
  { "virtually", "almost" },
  { "was a little", "was" },
  { "wasn't able to", "couldn't" },
  { "way in which", "way" },
  { "way more", "more" },
  { "we should take into account that", "we should consider" },
  { "well aware of", "aware" },
  { "well, at least", "at least" },
  { "well," },
  { "whether or not", "whether" },
  { "while at the same time", "while" },
  { "with the exception of", "except for" },
  { "with the purpose of", "to" },
  { "with the use of", "with" },
  { "within a short period of time", "quickly" },
  { "within close proximity", "near" },
  { "witnessed firsthand", "witnessed" },
  { "witnessed personally", "witnessed" },
  { "witnessed with my own eyes", "witnessed" },
  { "wonderful", "great" },
  { "worse than ever", "worse" },
  { "yet still", "yet" },
  { "you may be wondering", "you may wonder" },
  { "you should be aware that", "you should know" },
  { "you should be sure to", "be sure to" },
  { "you should keep in mind that", "remember" },
  { "you should know that", "know" },
  { "you should know about" },
  { "you will find", "you'll find" },
  { "you will notice", "you'll notice" },
  { "you will realize", "you'll realize" },
  { "you will see", "you'll see" },
  { "you will understand", "you'll understand" },
  { "you will want to", "you'll want to" },
  { "you would be able to", "you could" },
  { "you would be surprised", "you'd be surprised" },
  { "you would find", "you'd find" },
  { "you would notice", "you'd notice" },
  { "you would realize", "you'd realize" },
  { "you would see", "you'd see" },
  { "you would understand", "you'd understand" },
  { "you would want to", "you'd want to" },
}

-- Sort the replacements by length of the phrase to find, descending.
local function sort_replacements(replacements)
  table.sort(replacements, function(a, b)
    return #a[1] > #b[1]
  end)
  return replacements
end

M.rules = function()
  return sort_replacements(rules)
end

return M
